spring:
  application:
    name: osProject_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true&requireSSL=true&verifyServerCertificate=false
    password: ${DB_PW}
    username: ${DB_ID}
  jpa:
    hibernate:
      # naming:
        # physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_KEY}
  expiration: 3600000 # 30 minutes in milliseconds